# Generated by Django 5.2.8 on 2025-11-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(help_text='Ingrese el IVA Porcentual', max_length=100)),
                ('tax_percentege', models.CharField(help_text='Ingrese el IVA a Cobrar', max_length=12)),
                ('description', models.TextField(help_text='Ingrese la Descripcion del IVA')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', help_text='Ingrese el Estado del Gerente', max_length=8)),
            ],
            options={
                'verbose_name': 'tax',
                'verbose_name_plural': 'taxs',
            },
        ),
    ]
