# Generated by Django 5.2.8 on 2025-11-06 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_rename_branch_category'),
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(help_text='Ingrese el Codigo del Producto', max_length=20)),
                ('product_name', models.CharField(help_text='Ingrese el Nombre del Producto', max_length=100)),
                ('description', models.TextField(help_text='Ingrese la Descripcion del producto')),
                ('price', models.DecimalField(decimal_places=2, help_text='Ingrese el Precio del Producto', max_digits=10)),
                ('weinght', models.DecimalField(decimal_places=2, help_text='Ingrese el Peso del Producto', max_digits=10)),
                ('dimentions', models.CharField(help_text='Ingrese el Tamaño del Producto', max_length=100)),
                ('brand', models.CharField(help_text='Ingrese la Marca del Producto', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', help_text='Ingrese el Estado del Producto', max_length=8)),
                ('category', models.ForeignKey(help_text='Seleccione el Tipo de Producto', on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('tax', models.ForeignKey(help_text='Seleccione el Tipo de Impuesto', on_delete=django.db.models.deletion.CASCADE, to='tax.tax')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
