# Generated by Django 5.2.8 on 2025-11-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(help_text='Ingrese el Nombre de la Sucursal', max_length=100)),
                ('address', models.CharField(help_text='Ingrese la Direccion del Gerente', max_length=100)),
                ('phone', models.CharField(help_text='Ingrese el Telefono del Gerente', max_length=12)),
                ('email', models.EmailField(help_text='Ingrese el Correo del Gerente', max_length=100)),
                ('name', models.CharField(help_text='Ingrese el Nombre del Gerente', max_length=100)),
                ('opening_date', models.DateField(help_text='Ingrese la Fecha de Trabajo', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', help_text='Ingrese el Estado del Gerente', max_length=8)),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branchs',
            },
        ),
    ]
