# Generated by Django 5.2.8 on 2025-11-06 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branch',
            new_name='Category',
        ),
    ]
